spring:
  application:
    name:Campus Event
  datasource:
    url: jdbc:postgresql://localhost:5432/CEM
    driver-class-name: org.postgresql.Driver
    username: shrey
    password: shrey

  jpa:
    hibernate:
      ddl-auto: update

